# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'score_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(834, 394)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 781, 331))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tb_score = QtWidgets.QTextBrowser(self.frame)
        self.tb_score.setObjectName("tb_score")
        self.verticalLayout.addWidget(self.tb_score)
        self.b_exit = QtWidgets.QPushButton(self.frame)
        self.b_exit.setObjectName("b_exit")
        self.verticalLayout.addWidget(self.b_exit)

        # Увеличиваем шрифт
        font = QtGui.QFont()
        font.setPointSize(14)  # ← здесь меняешь размер
        self.tb_score.setFont(font)
        self.b_exit.setFont(font)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Score"))
        self.b_exit.setText(_translate("Dialog", "Выйти"))
